name: Build ESP32 Firmware (from b1kamp666 repo)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Install Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 2️⃣ Cache ESP-IDF toolchain + Python deps
      - name: Cache ESP-IDF
        uses: actions/cache@v4
        with:
          path: |
            ~/.espressif
            esp-idf
          key: ${{ runner.os }}-espidf-v5.5.1
          restore-keys: |
            ${{ runner.os }}-espidf-

      # 3️⃣ Clone ESP-IDF and install minimal ESP32 toolchain
      - name: Install ESP-IDF (ESP32 only)
        run: |
          python -m pip install --upgrade pip
          pip install cmake ninja
          if [ ! -d esp-idf ]; then
            git clone --recursive https://github.com/espressif/esp-idf.git -b v5.5.1 esp-idf
          fi
          cd esp-idf
          
          ./tools/idf_tools.py install --target esp32
          ./tools/idf_tools.py install-python-env
          cd ..
          echo "source $PWD/esp-idf/export.sh" >> $GITHUB_ENV

      # 4️⃣ Clone your NodeMCU ESP32 firmware repository
      - name: Clone NodeMCU firmware repo
        run: |
          git clone --recursive https://github.com/b1kamp666/nodemcu-esp32-firmware.git
          cd nodemcu-esp32-firmware
          if [ ! -d main/nanopb ]; then
            git clone https://github.com/nanopb/nanopb.git main/nanopb
          fi

      # 5️⃣ Build firmware in its root directory
      - name: Build ESP32 firmware
        run: |
          source $PWD/esp-idf/export.sh
