name: Build NodeMCU ESP32 Firmware

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true   # fetches submodules if any

      # 2️⃣ Clone nanopb if missing
      - name: Ensure nanopb exists
        run: |
          if [ ! -d main/nanopb ]; then
            git clone https://github.com/nanopb/nanopb.git main/nanopb
          fi

      # 3️⃣ Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 4️⃣ Install ESP-IDF
      - name: Install ESP-IDF
        uses: espressif/install-esp-idf-action@v1
        with:
          esp-idf-version: 'v5.5.1'

      # 5️⃣ Build firmware
      - name: Build project
        run: |
          idf.py fullclean
          idf.py build

      # 6️⃣ Upload firmware artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nodemcu-esp32-firmware
          path: build/*.bin
